### PR TITLE
Create cloudformation template

### PR DESCRIPTION
**Pull request by mikepugh**
This will help automate provisioning your solution. User only needs to upload `dist.zip` to one of their S3 buckets and then run the cloud formation template.

This could assist with issue #22

### CODE REVIEW

**Comment by alexforever86** [comment]
Do we have anything pending here?

**Comment by alexforever86** [comment]
We have the same cloudformation in yaml format. 
https://github.com/microservices-today/dynamodb-lambda-autoscale/blob/master/cloudformation.yaml

**Comment by asvarshn** [comment]
@alexforever86 getting 404

**Comment by mikepugh** [comment]
Closing due to lack of activity

**Pull request closed without merging**
